// Uncomment this line on creating a translation file
import { surveyLocalization } from "survey-core";

var englishStrings = {
  pagePrevText: "Anterior",
  pageNextText: "Siguiente",
  completeText: "Completar",
  previewText: "Previsualización",
  editText: "Editar",
  startSurveyText: "Inicio",
  otherItemText: "Otro (describe)",
  noneItemText: "Ninguno",
  selectAllItemText: "Seleccionar todo",
  progressText: "Página {0} de {1}",
  indexText: "{0} de {1}",
  panelDynamicProgressText: "{0} de {1}",
  questionsProgressText: "Respondidas {0}/{1} preguntas",
  emptySurvey: "No hay una página o pregunta visible.",
  completingSurvey: "¡Gracias por completar el censo!",
  completingSurveyBefore:
    "Nuestros registros muestran que ya ha completado este censo.",
  loadingSurvey: "Cargando...",
  placeholder: "Seleccione...",
  ratingOptionsCaption: "Toca aquí para calificar...",
  value: "valor",
  requiredError: "Respuesta requerida.",
  requiredErrorInPanel: "Respuesta requerida: responde al menos una pregunta.",
  requiredInAllRowsError:
    "Respuesta requerida: responde preguntas en todas las filas",
  numericError: "El valor debe ser numérico..",
  minError: "El valor no debe ser inferior a {0}",
  maxError: "El valor no debe ser mayor que {0}",
  textMinLength: "Introduzca al menos {0} carácter(es).",
  textMaxLength: "Por favor ingrese no más de {0} carácter(es).",
  textMinMaxLength: "Introduzca al menos {0} y no más que {1} carácteres.",
  minRowCountError: "Complete al menos {0} fila(s).",
  minSelectError: "Seleccione al menos {0} variante(s).",
  maxSelectError: "Por favor ingrese no más de {0} variante(s).",
  numericMinMax: "El '{0}' debe ser al menos {1} y como máximo {2}",
  numericMin: "El '{0}' debe ser al menos {1}",
  numericMax: "El '{0}' debe ser como máximo {1}",
  invalidEmail:
    "Por favor, introduce una dirección de correo electrónico válida.",
  invalidExpression: "La expresión: {0} debería devolver 'true'.",
  urlRequestError: "La solicitud devolvió un error '{0}'. {1}",
  urlGetChoicesError:
    "La solicitud devolvió datos vacíos o la propiedad 'path' es incorrecta",
  exceedMaxSize: "El tamaño del archivo no debe exceder {0}.",
  otherRequiredError: "Respuesta requerida: ingrese otro valor.",
  uploadingFile:
    "Su archivo se está cargando. Espere unos segundos y vuelva a intentarlo..",
  loadingFile: "Cargando...",
  chooseFile: "Seleccionar archivo(s)...",
  noFileChosen: "Ningún archivo seleccionado",
  fileDragAreaPlaceholder:
    "Suelte un archivo aquí o haga clic en el botón de abajo para cargar el archivo.",
  confirmDelete: "¿Quiere borrar el registro?",
  keyDuplicationError: "Este valor debe ser único.",
  addColumn: "Añadir columna",
  addRow: "Añadir fila",
  removeRow: "Remover",
  emptyRowsText: "No hay filas.",
  addPanel: "Añadir nuevo",
  removePanel: "Remover",
  choices_Item: "Item",
  matrix_column: "Columna",
  matrix_row: "Fila",
  multipletext_itemname: "Texto",
  savingData: "Los resultados se están guardando en el servidor....",
  savingDataError: "Ocurrió un error y no pudimos guardar los resultados.",
  savingDataSuccess: "¡Los resultados se guardaron con éxito!",
  saveAgainButton: "Intente nuevamente",
  timerMin: "min",
  timerSec: "seg",
  timerSpentAll: "Has gastado {0} en esta página y {1} en total.",
  timerSpentPage: "Has gastado {0} en esta página.",
  timerSpentSurvey: "Has gastado {0} en total.",
  timerLimitAll: "Has gastado {0} de {1} en esta página y {2} de {3} en total.",
  timerLimitPage: "Has gastado {0} de {1} en esta página.",
  timerLimitSurvey: "Has gastado {0} de {1} es total.",
  cleanCaption: "Limpiar",
  clearCaption: "Clear",
  signaturePlaceHolder: "Firma aquí",
  chooseFileCaption: "Seleccione el archivo",
  removeFileCaption: "Remover este archivo",
  booleanCheckedLabel: "Si",
  booleanUncheckedLabel: "No",
  confirmRemoveFile: "¿Estás seguro de que quieres eliminar este archivo: {0}?",
  confirmRemoveAllFiles:
    "¿Estás seguro de que quieres eliminar todos los archivos?",
  questionTitlePatternText: "Título de la pregunta",
  modalCancelButtonText: "Cancelar",
  modalApplyButtonText: "Aplicar",
  filterStringPlaceholder: "Escribe para buscar...",
  emptyMessage: "No hay información para mostrar",
  noEntriesText:
    "No hay entradas hasta ahora.\nHaga clic en el botón de abajo para agregar una nueva entrada.",
  more: "Más",
};
//Uncomment these two lines on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
surveyLocalization.locales["custom"] = englishStrings;
